package tgw.evolution.mixin;

import net.minecraft.client.model.*;
import net.minecraft.client.model.dragon.DragonHeadModel;
import net.minecraft.client.model.geom.LayerDefinitions;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.renderer.blockentity.*;
import net.minecraft.client.renderer.entity.EndCrystalRenderer;
import net.minecraft.client.renderer.entity.EnderDragonRenderer;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.client.renderer.entity.layers.SpinAttackEffectLayer;
import net.minecraft.world.entity.vehicle.Boat;
import net.minecraft.world.level.block.state.properties.WoodType;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Overwrite;
import org.spongepowered.asm.mixin.Shadow;
import tgw.evolution.client.models.entities.ModelPlayer;
import tgw.evolution.client.util.ModelUtils;
import tgw.evolution.hooks.ClientHooks;
import tgw.evolution.util.collection.maps.O2OHashMap;
import tgw.evolution.util.collection.maps.O2OMap;

import java.util.List;
import java.util.Map;

@Mixin(LayerDefinitions.class)
public abstract class MixinLayerDefinitions {

    @Shadow @Final private static CubeDeformation OUTER_ARMOR_DEFORMATION;
    @Shadow @Final private static CubeDeformation INNER_ARMOR_DEFORMATION;
    @Shadow @Final private static CubeDeformation FISH_PATTERN_DEFORMATION;

    /**
     * @author TheGreatWolf
     * @reason Modify various layers.
     */
    @Overwrite
    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        O2OMap<ModelLayerLocation, LayerDefinition> map = new O2OHashMap<>();
        LayerDefinition humanoid = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
        LayerDefinition outerArmor = LayerDefinition.create(HumanoidModel.createMesh(OUTER_ARMOR_DEFORMATION, 0.0F), 64, 32);
        LayerDefinition piglinOuterArmor = LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(1.02F), 0.0F), 64, 32);
        LayerDefinition innerArmor = LayerDefinition.create(HumanoidModel.createMesh(INNER_ARMOR_DEFORMATION, 0.0F), 64, 32);
        LayerDefinition minecart = MinecartModel.createBodyLayer();
        LayerDefinition mobHead = SkullModel.createMobHeadLayer();
        LayerDefinition horse = LayerDefinition.create(HorseModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition illager = IllagerModel.createBodyLayer();
        LayerDefinition cow = CowModel.createBodyLayer();
        LayerDefinition ocelot = LayerDefinition.create(OcelotModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition piglin = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition skull = SkullModel.createHumanoidHeadLayer();
        LayerDefinition llama = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition strider = StriderModel.createBodyLayer();
        LayerDefinition hoglin = HoglinModel.createBodyLayer();
        LayerDefinition skeleton = SkeletonModel.createBodyLayer();
        LayerDefinition villager = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64);
        LayerDefinition spider = SpiderModel.createSpiderBodyLayer();
        map.put(ModelLayers.ARMOR_STAND, ArmorStandModel.createBodyLayer());
        map.put(ModelLayers.ARMOR_STAND_INNER_ARMOR, ArmorStandArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        map.put(ModelLayers.ARMOR_STAND_OUTER_ARMOR, ArmorStandArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION));
        map.put(ModelLayers.AXOLOTL, AxolotlModel.createBodyLayer());
        map.put(ModelLayers.BANNER, BannerRenderer.createBodyLayer());
        map.put(ModelLayers.BAT, BatModel.createBodyLayer());
        map.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
        map.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
        map.put(ModelLayers.BEE, BeeModel.createBodyLayer());
        map.put(ModelLayers.BELL, BellRenderer.createBodyLayer());
        map.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
        map.put(ModelLayers.BOOK, BookModel.createBodyLayer());
        map.put(ModelLayers.CAT, ocelot);
        map.put(ModelLayers.CAT_COLLAR, LayerDefinition.create(OcelotModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32));
        map.put(ModelLayers.CAVE_SPIDER, spider);
        map.put(ModelLayers.CHEST, ChestRenderer.createSingleBodyLayer());
        map.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestRenderer.createDoubleBodyLeftLayer());
        map.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestRenderer.createDoubleBodyRightLayer());
        map.put(ModelLayers.CHEST_MINECART, minecart);
        map.put(ModelLayers.CHICKEN, ChickenModel.createBodyLayer());
        map.put(ModelLayers.COD, CodModel.createBodyLayer());
        map.put(ModelLayers.COMMAND_BLOCK_MINECART, minecart);
        map.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
        map.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
        map.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
        map.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
        map.put(ModelLayers.COW, cow);
        map.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
        map.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
        map.put(ModelLayers.CREEPER_HEAD, mobHead);
        map.put(ModelLayers.DOLPHIN, DolphinModel.createBodyLayer());
        map.put(ModelLayers.DONKEY, ChestedHorseModel.createBodyLayer());
        map.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
        map.put(ModelLayers.DROWNED, DrownedModel.createBodyLayer(CubeDeformation.NONE));
        map.put(ModelLayers.DROWNED_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.DROWNED_OUTER_ARMOR, innerArmor);
        map.put(ModelLayers.DROWNED_OUTER_LAYER, DrownedModel.createBodyLayer(ModelUtils.DEF_025));
        map.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createBodyLayer());
        map.put(ModelLayers.ELYTRA, ElytraModel.createLayer());
        map.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
        map.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
        map.put(ModelLayers.ENDER_DRAGON, EnderDragonRenderer.createBodyLayer());
        map.put(ModelLayers.END_CRYSTAL, EndCrystalRenderer.createBodyLayer());
        map.put(ModelLayers.EVOKER, illager);
        map.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
        map.put(ModelLayers.FOX, FoxModel.createBodyLayer());
        map.put(ModelLayers.FURNACE_MINECART, minecart);
        map.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
        map.put(ModelLayers.GIANT, humanoid);
        map.put(ModelLayers.GIANT_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.GIANT_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.GLOW_SQUID, SquidModel.createBodyLayer());
        map.put(ModelLayers.GOAT, GoatModel.createBodyLayer());
        map.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
        map.put(ModelLayers.HOGLIN, hoglin);
        map.put(ModelLayers.HOPPER_MINECART, minecart);
        map.put(ModelLayers.HORSE, horse);
        map.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(HorseModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
        map.put(ModelLayers.HUSK, humanoid);
        map.put(ModelLayers.HUSK_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.HUSK_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.ILLUSIONER, illager);
        map.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
        map.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
        map.put(ModelLayers.LLAMA, llama);
        map.put(ModelLayers.LLAMA_DECOR, LlamaModel.createBodyLayer(ModelUtils.DEF_05));
        map.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
        map.put(ModelLayers.MAGMA_CUBE, LavaSlimeModel.createBodyLayer());
        map.put(ModelLayers.MINECART, minecart);
        map.put(ModelLayers.MOOSHROOM, cow);
        map.put(ModelLayers.MULE, ChestedHorseModel.createBodyLayer());
        map.put(ModelLayers.OCELOT, ocelot);
        map.put(ModelLayers.PANDA, PandaModel.createBodyLayer());
        map.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
        map.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
        map.put(ModelLayers.PIG, PigModel.createBodyLayer(CubeDeformation.NONE));
        map.put(ModelLayers.PIG_SADDLE, PigModel.createBodyLayer(ModelUtils.DEF_05));
        map.put(ModelLayers.PIGLIN, piglin);
        map.put(ModelLayers.PIGLIN_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.PIGLIN_OUTER_ARMOR, piglinOuterArmor);
        map.put(ModelLayers.PIGLIN_BRUTE, piglin);
        map.put(ModelLayers.PIGLIN_BRUTE_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, piglinOuterArmor);
        map.put(ModelLayers.PILLAGER, illager);
        map.put(ModelLayers.PLAYER, LayerDefinition.create(ModelPlayer.createMesh(CubeDeformation.NONE, false), 64, 64));
        map.put(ModelLayers.PLAYER_HEAD, skull);
        map.put(ModelLayers.PLAYER_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.PLAYER_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(ModelPlayer.createMesh(CubeDeformation.NONE, true), 64, 64));
        map.put(ModelLayers.PLAYER_SLIM_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.PLAYER_SLIM_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectLayer.createLayer());
        map.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer());
        map.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
        map.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
        map.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
        map.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer());
        map.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
        map.put(ModelLayers.SALMON, SalmonModel.createBodyLayer());
        map.put(ModelLayers.SHEEP, SheepModel.createBodyLayer());
        map.put(ModelLayers.SHEEP_FUR, SheepFurModel.createFurLayer());
        map.put(ModelLayers.SHIELD, ShieldModel.createLayer());
        map.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
        map.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
        map.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
        map.put(ModelLayers.SKELETON, skeleton);
        map.put(ModelLayers.SKELETON_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.SKELETON_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.SKELETON_HORSE, horse);
        map.put(ModelLayers.SKELETON_SKULL, mobHead);
        map.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
        map.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
        map.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
        map.put(ModelLayers.SPAWNER_MINECART, minecart);
        map.put(ModelLayers.SPIDER, spider);
        map.put(ModelLayers.SQUID, SquidModel.createBodyLayer());
        map.put(ModelLayers.STRAY, skeleton);
        map.put(ModelLayers.STRAY_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.STRAY_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(ModelUtils.DEF_025, 0), 64, 32));
        map.put(ModelLayers.STRIDER, strider);
        map.put(ModelLayers.STRIDER_SADDLE, strider);
        map.put(ModelLayers.TNT_MINECART, minecart);
        map.put(ModelLayers.TRADER_LLAMA, llama);
        map.put(ModelLayers.TRIDENT, TridentModel.createLayer());
        map.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
        map.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
        map.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
        map.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
        map.put(ModelLayers.TURTLE, TurtleModel.createBodyLayer());
        map.put(ModelLayers.VEX, VexModel.createBodyLayer());
        map.put(ModelLayers.VILLAGER, villager);
        map.put(ModelLayers.VINDICATOR, illager);
        map.put(ModelLayers.WANDERING_TRADER, villager);
        map.put(ModelLayers.WITCH, WitchModel.createBodyLayer());
        map.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        map.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        map.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
        map.put(ModelLayers.WITHER_SKELETON, skeleton);
        map.put(ModelLayers.WITHER_SKELETON_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.WITHER_SKELETON_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.WITHER_SKELETON_SKULL, mobHead);
        map.put(ModelLayers.WOLF, WolfModel.createBodyLayer());
        map.put(ModelLayers.ZOGLIN, hoglin);
        map.put(ModelLayers.ZOMBIE, humanoid);
        map.put(ModelLayers.ZOMBIE_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.ZOMBIE_OUTER_ARMOR, outerArmor);
        map.put(ModelLayers.ZOMBIE_HEAD, skull);
        map.put(ModelLayers.ZOMBIE_HORSE, horse);
        map.put(ModelLayers.ZOMBIE_VILLAGER, ZombieVillagerModel.createBodyLayer());
        map.put(ModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION));
        map.put(ModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION));
        map.put(ModelLayers.ZOMBIFIED_PIGLIN, piglin);
        map.put(ModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, innerArmor);
        map.put(ModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, piglinOuterArmor);
        LayerDefinition boat = BoatModel.createBodyModel();
        for (Boat.Type type : Boat.Type.values()) {
            //noinspection ObjectAllocationInLoop
            map.put(ModelLayers.createBoatModelName(type), boat);
        }
        LayerDefinition sign = SignRenderer.createSignLayer();
        WoodType.values().forEach(t -> map.put(ModelLayers.createSignModelName(t), sign));
        ClientHooks.loadLayerDefinitions(map);
        List<ModelLayerLocation> list = ModelLayers.getKnownLocations().filter(l -> !map.containsKey(l)).toList();
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + list);
        }
        return map.view();
    }
}
