@FieldsAreNotNullByDefault
@MethodsReturnNotNullByDefault
@ParametersAreNotNullByDefault
package tgw.evolution.capabilities.player;

import tgw.evolution.util.FieldsAreNotNullByDefault;
import tgw.evolution.util.MethodsReturnNotNullByDefault;
import tgw.evolution.util.ParametersAreNotNullByDefault;