package tgw.evolution.client.models.tile;

import net.minecraft.client.renderer.entity.model.RendererModel;
import net.minecraft.client.renderer.model.Model;
import tgw.evolution.util.MathHelper;

public class ModelTileMolding extends Model {

    private final RendererModel AA1;
    private final RendererModel AB1;
    private final RendererModel AC1;
    private final RendererModel AD1;
    private final RendererModel AE1;
    private final RendererModel BA1;
    private final RendererModel BB1;
    private final RendererModel BC1;
    private final RendererModel BD1;
    private final RendererModel BE1;
    private final RendererModel CA1;
    private final RendererModel CB1;
    private final RendererModel CC1;
    private final RendererModel CD1;
    private final RendererModel CE1;
    private final RendererModel DA1;
    private final RendererModel DB1;
    private final RendererModel DC1;
    private final RendererModel DD1;
    private final RendererModel DE1;
    private final RendererModel EA1;
    private final RendererModel EB1;
    private final RendererModel EC1;
    private final RendererModel ED1;
    private final RendererModel EE1;
    private final RendererModel AA2;
    private final RendererModel AB2;
    private final RendererModel AC2;
    private final RendererModel AD2;
    private final RendererModel AE2;
    private final RendererModel BA2;
    private final RendererModel BB2;
    private final RendererModel BC2;
    private final RendererModel BD2;
    private final RendererModel BE2;
    private final RendererModel CA2;
    private final RendererModel CB2;
    private final RendererModel CC2;
    private final RendererModel CD2;
    private final RendererModel CE2;
    private final RendererModel DA2;
    private final RendererModel DB2;
    private final RendererModel DC2;
    private final RendererModel DD2;
    private final RendererModel DE2;
    private final RendererModel EA2;
    private final RendererModel EB2;
    private final RendererModel EC2;
    private final RendererModel ED2;
    private final RendererModel EE2;
    private final RendererModel AA3;
    private final RendererModel AB3;
    private final RendererModel AC3;
    private final RendererModel AD3;
    private final RendererModel AE3;
    private final RendererModel BA3;
    private final RendererModel BB3;
    private final RendererModel BC3;
    private final RendererModel BD3;
    private final RendererModel BE3;
    private final RendererModel CA3;
    private final RendererModel CB3;
    private final RendererModel CC3;
    private final RendererModel CD3;
    private final RendererModel CE3;
    private final RendererModel DA3;
    private final RendererModel DB3;
    private final RendererModel DC3;
    private final RendererModel DD3;
    private final RendererModel DE3;
    private final RendererModel EA3;
    private final RendererModel EB3;
    private final RendererModel EC3;
    private final RendererModel ED3;
    private final RendererModel EE3;
    private final RendererModel AA4;
    private final RendererModel AB4;
    private final RendererModel AC4;
    private final RendererModel AD4;
    private final RendererModel AE4;
    private final RendererModel BA4;
    private final RendererModel BB4;
    private final RendererModel BC4;
    private final RendererModel BD4;
    private final RendererModel BE4;
    private final RendererModel CA4;
    private final RendererModel CB4;
    private final RendererModel CC4;
    private final RendererModel CD4;
    private final RendererModel CE4;
    private final RendererModel DA4;
    private final RendererModel DB4;
    private final RendererModel DC4;
    private final RendererModel DD4;
    private final RendererModel DE4;
    private final RendererModel EA4;
    private final RendererModel EB4;
    private final RendererModel EC4;
    private final RendererModel ED4;
    private final RendererModel EE4;
    private final RendererModel AA5;
    private final RendererModel AB5;
    private final RendererModel AC5;
    private final RendererModel AD5;
    private final RendererModel AE5;
    private final RendererModel BA5;
    private final RendererModel BB5;
    private final RendererModel BC5;
    private final RendererModel BD5;
    private final RendererModel BE5;
    private final RendererModel CA5;
    private final RendererModel CB5;
    private final RendererModel CC5;
    private final RendererModel CD5;
    private final RendererModel CE5;
    private final RendererModel DA5;
    private final RendererModel DB5;
    private final RendererModel DC5;
    private final RendererModel DD5;
    private final RendererModel DE5;
    private final RendererModel EA5;
    private final RendererModel EB5;
    private final RendererModel EC5;
    private final RendererModel ED5;
    private final RendererModel EE5;
    public final RendererModel[][] layer1;
    public final RendererModel[][] layer2;
    public final RendererModel[][] layer3;
    public final RendererModel[][] layer4;
    public final RendererModel[][] layer5;
    private final RendererModel base;
    private final RendererModel baseN;
    private final RendererModel baseS;
    private final RendererModel baseW;
    private final RendererModel baseE;
    private final RendererModel[][][] layers;

    public ModelTileMolding() {
        super.textureWidth = 128;
        super.textureHeight = 40;
        this.base = new RendererModel(this, 0, 0);
        this.base.addBox(0.0F, 0.0F, 0.0F, 32, 1, 32);
        this.baseN = new RendererModel(this, 0, 33);
        this.baseN.addBox(0.0F, 1.0F, 0.0F, 32, 5, 1);
        this.baseS = new RendererModel(this, 0, 33);
        this.baseS.addBox(0.0F, 1.0F, 31.0F, 32, 5, 1);
        this.baseW = new RendererModel(this, 66, 33);
        this.baseW.addBox(-31.0F, 1.0F, 0.0F, 30, 5, 1);
        setRotationAngle(this.baseW, MathHelper.degToRad(90.0F), MathHelper.degToRad(90.0F), MathHelper.degToRad(90.0F));
        this.baseE = new RendererModel(this, 66, 33);
        this.baseE.addBox(-31.0F, 1.0F, 31.0F, 30, 5, 1);
        setRotationAngle(this.baseE, MathHelper.degToRad(90.0F), MathHelper.degToRad(90.0F), MathHelper.degToRad(90.0F));
        this.AA1 = new RendererModel(this, 0, 0);
        this.AA1.addBox(1.0F, 0.0F, 1.0F, 6, 6, 6);
        this.AB1 = new RendererModel(this, 0, 0);
        this.AB1.addBox(7.0F, 0.0F, 1.0F, 6, 6, 6);
        this.AC1 = new RendererModel(this, 0, 0);
        this.AC1.addBox(13.0F, 0.0F, 1.0F, 6, 6, 6);
        this.AD1 = new RendererModel(this, 0, 0);
        this.AD1.addBox(19.0F, 0.0F, 1.0F, 6, 6, 6);
        this.AE1 = new RendererModel(this, 0, 0);
        this.AE1.addBox(25.0F, 0.0F, 1.0F, 6, 6, 6);
        this.BA1 = new RendererModel(this, 0, 0);
        this.BA1.addBox(1.0F, 0.0F, 7.0F, 6, 6, 6);
        this.BB1 = new RendererModel(this, 0, 0);
        this.BB1.addBox(7.0F, 0.0F, 7.0F, 6, 6, 6);
        this.BC1 = new RendererModel(this, 0, 0);
        this.BC1.addBox(13.0F, 0.0F, 7.0F, 6, 6, 6);
        this.BD1 = new RendererModel(this, 0, 0);
        this.BD1.addBox(19.0F, 0.0F, 7.0F, 6, 6, 6);
        this.BE1 = new RendererModel(this, 0, 0);
        this.BE1.addBox(25.0F, 0.0F, 7.0F, 6, 6, 6);
        this.CA1 = new RendererModel(this, 0, 0);
        this.CA1.addBox(1.0F, 0.0F, 13.0F, 6, 6, 6);
        this.CB1 = new RendererModel(this, 0, 0);
        this.CB1.addBox(7.0F, 0.0F, 13.0F, 6, 6, 6);
        this.CC1 = new RendererModel(this, 0, 0);
        this.CC1.addBox(13.0F, 0.0F, 13.0F, 6, 6, 6);
        this.CD1 = new RendererModel(this, 0, 0);
        this.CD1.addBox(19.0F, 0.0F, 13.0F, 6, 6, 6);
        this.CE1 = new RendererModel(this, 0, 0);
        this.CE1.addBox(25.0F, 0.0F, 13.0F, 6, 6, 6);
        this.DA1 = new RendererModel(this, 0, 0);
        this.DA1.addBox(1.0F, 0.0F, 19.0F, 6, 6, 6);
        this.DB1 = new RendererModel(this, 0, 0);
        this.DB1.addBox(7.0F, 0.0F, 19.0F, 6, 6, 6);
        this.DC1 = new RendererModel(this, 0, 0);
        this.DC1.addBox(13.0F, 0.0F, 19.0F, 6, 6, 6);
        this.DD1 = new RendererModel(this, 0, 0);
        this.DD1.addBox(19.0F, 0.0F, 19.0F, 6, 6, 6);
        this.DE1 = new RendererModel(this, 0, 0);
        this.DE1.addBox(25.0F, 0.0F, 19.0F, 6, 6, 6);
        this.EA1 = new RendererModel(this, 0, 0);
        this.EA1.addBox(1.0F, 0.0F, 25.0F, 6, 6, 6);
        this.EB1 = new RendererModel(this, 0, 0);
        this.EB1.addBox(7.0F, 0.0F, 25.0F, 6, 6, 6);
        this.EC1 = new RendererModel(this, 0, 0);
        this.EC1.addBox(13.0F, 0.0F, 25.0F, 6, 6, 6);
        this.ED1 = new RendererModel(this, 0, 0);
        this.ED1.addBox(19.0F, 0.0F, 25.0F, 6, 6, 6);
        this.EE1 = new RendererModel(this, 0, 0);
        this.EE1.addBox(25.0F, 0.0F, 25.0F, 6, 6, 6);
        this.AA2 = new RendererModel(this, 0, 0);
        this.AA2.addBox(1.0F, 6.0F, 1.0F, 6, 6, 6);
        this.AB2 = new RendererModel(this, 0, 0);
        this.AB2.addBox(7.0F, 6.0F, 1.0F, 6, 6, 6);
        this.AC2 = new RendererModel(this, 0, 0);
        this.AC2.addBox(13.0F, 6.0F, 1.0F, 6, 6, 6);
        this.AD2 = new RendererModel(this, 0, 0);
        this.AD2.addBox(19.0F, 6.0F, 1.0F, 6, 6, 6);
        this.AE2 = new RendererModel(this, 0, 0);
        this.AE2.addBox(25.0F, 6.0F, 1.0F, 6, 6, 6);
        this.BA2 = new RendererModel(this, 0, 0);
        this.BA2.addBox(1.0F, 6.0F, 7.0F, 6, 6, 6);
        this.BB2 = new RendererModel(this, 0, 0);
        this.BB2.addBox(7.0F, 6.0F, 7.0F, 6, 6, 6);
        this.BC2 = new RendererModel(this, 0, 0);
        this.BC2.addBox(13.0F, 6.0F, 7.0F, 6, 6, 6);
        this.BD2 = new RendererModel(this, 0, 0);
        this.BD2.addBox(19.0F, 6.0F, 7.0F, 6, 6, 6);
        this.BE2 = new RendererModel(this, 0, 0);
        this.BE2.addBox(25.0F, 6.0F, 7.0F, 6, 6, 6);
        this.CA2 = new RendererModel(this, 0, 0);
        this.CA2.addBox(1.0F, 6.0F, 13.0F, 6, 6, 6);
        this.CB2 = new RendererModel(this, 0, 0);
        this.CB2.addBox(7.0F, 6.0F, 13.0F, 6, 6, 6);
        this.CC2 = new RendererModel(this, 0, 0);
        this.CC2.addBox(13.0F, 6.0F, 13.0F, 6, 6, 6);
        this.CD2 = new RendererModel(this, 0, 0);
        this.CD2.addBox(19.0F, 6.0F, 13.0F, 6, 6, 6);
        this.CE2 = new RendererModel(this, 0, 0);
        this.CE2.addBox(25.0F, 6.0F, 13.0F, 6, 6, 6);
        this.DA2 = new RendererModel(this, 0, 0);
        this.DA2.addBox(1.0F, 6.0F, 19.0F, 6, 6, 6);
        this.DB2 = new RendererModel(this, 0, 0);
        this.DB2.addBox(7.0F, 6.0F, 19.0F, 6, 6, 6);
        this.DC2 = new RendererModel(this, 0, 0);
        this.DC2.addBox(13.0F, 6.0F, 19.0F, 6, 6, 6);
        this.DD2 = new RendererModel(this, 0, 0);
        this.DD2.addBox(19.0F, 6.0F, 19.0F, 6, 6, 6);
        this.DE2 = new RendererModel(this, 0, 0);
        this.DE2.addBox(25.0F, 6.0F, 19.0F, 6, 6, 6);
        this.EA2 = new RendererModel(this, 0, 0);
        this.EA2.addBox(1.0F, 6.0F, 25.0F, 6, 6, 6);
        this.EB2 = new RendererModel(this, 0, 0);
        this.EB2.addBox(7.0F, 6.0F, 25.0F, 6, 6, 6);
        this.EC2 = new RendererModel(this, 0, 0);
        this.EC2.addBox(13.0F, 6.0F, 25.0F, 6, 6, 6);
        this.ED2 = new RendererModel(this, 0, 0);
        this.ED2.addBox(19.0F, 6.0F, 25.0F, 6, 6, 6);
        this.EE2 = new RendererModel(this, 0, 0);
        this.EE2.addBox(25.0F, 6.0F, 25.0F, 6, 6, 6);
        this.AA3 = new RendererModel(this, 0, 0);
        this.AA3.addBox(1.0F, 12.0F, 1.0F, 6, 6, 6);
        this.AB3 = new RendererModel(this, 0, 0);
        this.AB3.addBox(7.0F, 12.0F, 1.0F, 6, 6, 6);
        this.AC3 = new RendererModel(this, 0, 0);
        this.AC3.addBox(13.0F, 12.0F, 1.0F, 6, 6, 6);
        this.AD3 = new RendererModel(this, 0, 0);
        this.AD3.addBox(19.0F, 12.0F, 1.0F, 6, 6, 6);
        this.AE3 = new RendererModel(this, 0, 0);
        this.AE3.addBox(25.0F, 12.0F, 1.0F, 6, 6, 6);
        this.BA3 = new RendererModel(this, 0, 0);
        this.BA3.addBox(1.0F, 12.0F, 7.0F, 6, 6, 6);
        this.BB3 = new RendererModel(this, 0, 0);
        this.BB3.addBox(7.0F, 12.0F, 7.0F, 6, 6, 6);
        this.BC3 = new RendererModel(this, 0, 0);
        this.BC3.addBox(13.0F, 12.0F, 7.0F, 6, 6, 6);
        this.BD3 = new RendererModel(this, 0, 0);
        this.BD3.addBox(19.0F, 12.0F, 7.0F, 6, 6, 6);
        this.BE3 = new RendererModel(this, 0, 0);
        this.BE3.addBox(25.0F, 12.0F, 7.0F, 6, 6, 6);
        this.CA3 = new RendererModel(this, 0, 0);
        this.CA3.addBox(1.0F, 12.0F, 13.0F, 6, 6, 6);
        this.CB3 = new RendererModel(this, 0, 0);
        this.CB3.addBox(7.0F, 12.0F, 13.0F, 6, 6, 6);
        this.CC3 = new RendererModel(this, 0, 0);
        this.CC3.addBox(13.0F, 12.0F, 13.0F, 6, 6, 6);
        this.CD3 = new RendererModel(this, 0, 0);
        this.CD3.addBox(19.0F, 12.0F, 13.0F, 6, 6, 6);
        this.CE3 = new RendererModel(this, 0, 0);
        this.CE3.addBox(25.0F, 12.0F, 13.0F, 6, 6, 6);
        this.DA3 = new RendererModel(this, 0, 0);
        this.DA3.addBox(1.0F, 12.0F, 19.0F, 6, 6, 6);
        this.DB3 = new RendererModel(this, 0, 0);
        this.DB3.addBox(7.0F, 12.0F, 19.0F, 6, 6, 6);
        this.DC3 = new RendererModel(this, 0, 0);
        this.DC3.addBox(13.0F, 12.0F, 19.0F, 6, 6, 6);
        this.DD3 = new RendererModel(this, 0, 0);
        this.DD3.addBox(19.0F, 12.0F, 19.0F, 6, 6, 6);
        this.DE3 = new RendererModel(this, 0, 0);
        this.DE3.addBox(25.0F, 12.0F, 19.0F, 6, 6, 6);
        this.EA3 = new RendererModel(this, 0, 0);
        this.EA3.addBox(1.0F, 12.0F, 25.0F, 6, 6, 6);
        this.EB3 = new RendererModel(this, 0, 0);
        this.EB3.addBox(7.0F, 12.0F, 25.0F, 6, 6, 6);
        this.EC3 = new RendererModel(this, 0, 0);
        this.EC3.addBox(13.0F, 12.0F, 25.0F, 6, 6, 6);
        this.ED3 = new RendererModel(this, 0, 0);
        this.ED3.addBox(19.0F, 12.0F, 25.0F, 6, 6, 6);
        this.EE3 = new RendererModel(this, 0, 0);
        this.EE3.addBox(25.0F, 12.0F, 25.0F, 6, 6, 6);
        this.AA4 = new RendererModel(this, 0, 0);
        this.AA4.addBox(1.0F, 18.0F, 1.0F, 6, 6, 6);
        this.AB4 = new RendererModel(this, 0, 0);
        this.AB4.addBox(7.0F, 18.0F, 1.0F, 6, 6, 6);
        this.AC4 = new RendererModel(this, 0, 0);
        this.AC4.addBox(13.0F, 18.0F, 1.0F, 6, 6, 6);
        this.AD4 = new RendererModel(this, 0, 0);
        this.AD4.addBox(19.0F, 18.0F, 1.0F, 6, 6, 6);
        this.AE4 = new RendererModel(this, 0, 0);
        this.AE4.addBox(25.0F, 18.0F, 1.0F, 6, 6, 6);
        this.BA4 = new RendererModel(this, 0, 0);
        this.BA4.addBox(1.0F, 18.0F, 7.0F, 6, 6, 6);
        this.BB4 = new RendererModel(this, 0, 0);
        this.BB4.addBox(7.0F, 18.0F, 7.0F, 6, 6, 6);
        this.BC4 = new RendererModel(this, 0, 0);
        this.BC4.addBox(13.0F, 18.0F, 7.0F, 6, 6, 6);
        this.BD4 = new RendererModel(this, 0, 0);
        this.BD4.addBox(19.0F, 18.0F, 7.0F, 6, 6, 6);
        this.BE4 = new RendererModel(this, 0, 0);
        this.BE4.addBox(25.0F, 18.0F, 7.0F, 6, 6, 6);
        this.CA4 = new RendererModel(this, 0, 0);
        this.CA4.addBox(1.0F, 18.0F, 13.0F, 6, 6, 6);
        this.CB4 = new RendererModel(this, 0, 0);
        this.CB4.addBox(7.0F, 18.0F, 13.0F, 6, 6, 6);
        this.CC4 = new RendererModel(this, 0, 0);
        this.CC4.addBox(13.0F, 18.0F, 13.0F, 6, 6, 6);
        this.CD4 = new RendererModel(this, 0, 0);
        this.CD4.addBox(19.0F, 18.0F, 13.0F, 6, 6, 6);
        this.CE4 = new RendererModel(this, 0, 0);
        this.CE4.addBox(25.0F, 18.0F, 13.0F, 6, 6, 6);
        this.DA4 = new RendererModel(this, 0, 0);
        this.DA4.addBox(1.0F, 18.0F, 19.0F, 6, 6, 6);
        this.DB4 = new RendererModel(this, 0, 0);
        this.DB4.addBox(7.0F, 18.0F, 19.0F, 6, 6, 6);
        this.DC4 = new RendererModel(this, 0, 0);
        this.DC4.addBox(13.0F, 18.0F, 19.0F, 6, 6, 6);
        this.DD4 = new RendererModel(this, 0, 0);
        this.DD4.addBox(19.0F, 18.0F, 19.0F, 6, 6, 6);
        this.DE4 = new RendererModel(this, 0, 0);
        this.DE4.addBox(25.0F, 18.0F, 19.0F, 6, 6, 6);
        this.EA4 = new RendererModel(this, 0, 0);
        this.EA4.addBox(1.0F, 18.0F, 25.0F, 6, 6, 6);
        this.EB4 = new RendererModel(this, 0, 0);
        this.EB4.addBox(7.0F, 18.0F, 25.0F, 6, 6, 6);
        this.EC4 = new RendererModel(this, 0, 0);
        this.EC4.addBox(13.0F, 18.0F, 25.0F, 6, 6, 6);
        this.ED4 = new RendererModel(this, 0, 0);
        this.ED4.addBox(19.0F, 18.0F, 25.0F, 6, 6, 6);
        this.EE4 = new RendererModel(this, 0, 0);
        this.EE4.addBox(25.0F, 18.0F, 25.0F, 6, 6, 6);
        this.AA5 = new RendererModel(this, 0, 0);
        this.AA5.addBox(1.0F, 24.0F, 1.0F, 6, 6, 6);
        this.AB5 = new RendererModel(this, 0, 0);
        this.AB5.addBox(7.0F, 24.0F, 1.0F, 6, 6, 6);
        this.AC5 = new RendererModel(this, 0, 0);
        this.AC5.addBox(13.0F, 24.0F, 1.0F, 6, 6, 6);
        this.AD5 = new RendererModel(this, 0, 0);
        this.AD5.addBox(19.0F, 24.0F, 1.0F, 6, 6, 6);
        this.AE5 = new RendererModel(this, 0, 0);
        this.AE5.addBox(25.0F, 24.0F, 1.0F, 6, 6, 6);
        this.BA5 = new RendererModel(this, 0, 0);
        this.BA5.addBox(1.0F, 24.0F, 7.0F, 6, 6, 6);
        this.BB5 = new RendererModel(this, 0, 0);
        this.BB5.addBox(7.0F, 24.0F, 7.0F, 6, 6, 6);
        this.BC5 = new RendererModel(this, 0, 0);
        this.BC5.addBox(13.0F, 24.0F, 7.0F, 6, 6, 6);
        this.BD5 = new RendererModel(this, 0, 0);
        this.BD5.addBox(19.0F, 24.0F, 7.0F, 6, 6, 6);
        this.BE5 = new RendererModel(this, 0, 0);
        this.BE5.addBox(25.0F, 24.0F, 7.0F, 6, 6, 6);
        this.CA5 = new RendererModel(this, 0, 0);
        this.CA5.addBox(1.0F, 24.0F, 13.0F, 6, 6, 6);
        this.CB5 = new RendererModel(this, 0, 0);
        this.CB5.addBox(7.0F, 24.0F, 13.0F, 6, 6, 6);
        this.CC5 = new RendererModel(this, 0, 0);
        this.CC5.addBox(13.0F, 24.0F, 13.0F, 6, 6, 6);
        this.CD5 = new RendererModel(this, 0, 0);
        this.CD5.addBox(19.0F, 24.0F, 13.0F, 6, 6, 6);
        this.CE5 = new RendererModel(this, 0, 0);
        this.CE5.addBox(25.0F, 24.0F, 13.0F, 6, 6, 6);
        this.DA5 = new RendererModel(this, 0, 0);
        this.DA5.addBox(1.0F, 24.0F, 19.0F, 6, 6, 6);
        this.DB5 = new RendererModel(this, 0, 0);
        this.DB5.addBox(7.0F, 24.0F, 19.0F, 6, 6, 6);
        this.DC5 = new RendererModel(this, 0, 0);
        this.DC5.addBox(13.0F, 24.0F, 19.0F, 6, 6, 6);
        this.DD5 = new RendererModel(this, 0, 0);
        this.DD5.addBox(19.0F, 24.0F, 19.0F, 6, 6, 6);
        this.DE5 = new RendererModel(this, 0, 0);
        this.DE5.addBox(25.0F, 24.0F, 19.0F, 6, 6, 6);
        this.EA5 = new RendererModel(this, 0, 0);
        this.EA5.addBox(1.0F, 24.0F, 25.0F, 6, 6, 6);
        this.EB5 = new RendererModel(this, 0, 0);
        this.EB5.addBox(7.0F, 24.0F, 25.0F, 6, 6, 6);
        this.EC5 = new RendererModel(this, 0, 0);
        this.EC5.addBox(13.0F, 24.0F, 25.0F, 6, 6, 6);
        this.ED5 = new RendererModel(this, 0, 0);
        this.ED5.addBox(19.0F, 24.0F, 25.0F, 6, 6, 6);
        this.EE5 = new RendererModel(this, 0, 0);
        this.EE5.addBox(25.0F, 24.0F, 25.0F, 6, 6, 6);
        this.layer1 = new RendererModel[][] {{this.AA1, this.BA1, this.CA1, this.DA1, this.EA1},
                                             {this.AB1, this.BB1, this.CB1, this.DB1, this.EB1},
                                             {this.AC1, this.BC1, this.CC1, this.DC1, this.EC1},
                                             {this.AD1, this.BD1, this.CD1, this.DD1, this.ED1},
                                             {this.AE1, this.BE1, this.CE1, this.DE1, this.EE1}};
        this.layer2 = new RendererModel[][] {{this.AA2, this.BA2, this.CA2, this.DA2, this.EA2},
                                             {this.AB2, this.BB2, this.CB2, this.DB2, this.EB2},
                                             {this.AC2, this.BC2, this.CC2, this.DC2, this.EC2},
                                             {this.AD2, this.BD2, this.CD2, this.DD2, this.ED2},
                                             {this.AE2, this.BE2, this.CE2, this.DE2, this.EE2}};
        this.layer3 = new RendererModel[][] {{this.AA3, this.BA3, this.CA3, this.DA3, this.EA3},
                                             {this.AB3, this.BB3, this.CB3, this.DB3, this.EB3},
                                             {this.AC3, this.BC3, this.CC3, this.DC3, this.EC3},
                                             {this.AD3, this.BD3, this.CD3, this.DD3, this.ED3},
                                             {this.AE3, this.BE3, this.CE3, this.DE3, this.EE3}};
        this.layer4 = new RendererModel[][] {{this.AA4, this.BA4, this.CA4, this.DA4, this.EA4},
                                             {this.AB4, this.BB4, this.CB4, this.DB4, this.EB4},
                                             {this.AC4, this.BC4, this.CC4, this.DC4, this.EC4},
                                             {this.AD4, this.BD4, this.CD4, this.DD4, this.ED4},
                                             {this.AE4, this.BE4, this.CE4, this.DE4, this.EE4}};
        this.layer5 = new RendererModel[][] {{this.AA5, this.BA5, this.CA5, this.DA5, this.EA5},
                                             {this.AB5, this.BB5, this.CB5, this.DB5, this.EB5},
                                             {this.AC5, this.BC5, this.CC5, this.DC5, this.EC5},
                                             {this.AD5, this.BD5, this.CD5, this.DD5, this.ED5},
                                             {this.AE5, this.BE5, this.CE5, this.DE5, this.EE5}};
        this.layers = new RendererModel[][][] {this.layer1, this.layer2, this.layer3, this.layer4, this.layer5};
    }

    public static void setRotationAngle(RendererModel modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    public void renderLayer(boolean[][] matrix, int index) {
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[0].length; j++) {
                if (matrix[i][j]) {
                    this.layers[index][i][j].render(1.0F / 32.0F);
                }
            }
        }
    }

    public void renderBase() {
        this.base.render(1.0F / 32.0F);
        this.baseN.render(1.0F / 32.0F);
        this.baseS.render(1.0F / 32.0F);
        this.baseW.render(1.0F / 32.0F);
        this.baseE.render(1.0F / 32.0F);
    }
}
